#!/usr/bin/env python3
"""Render the original demonstration assets into ``assets/demo``.

All content is generated by :mod:`artrestore_imaging.demo`; nothing is fetched
from the internet. Run after changing the generators:

    python scripts/generate_demo_assets.py
"""

from __future__ import annotations

import argparse
import io
import json
import pathlib
import sys

import cv2
import numpy as np
from PIL import Image

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "services" / "image-processing" / "src"))

from artrestore_imaging import demo  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "assets" / "demo"
WEB_PUBLIC = REPO_ROOT / "apps" / "web" / "public" / "demo"
WEB_MAX_WIDTH = 1100


def _encode(rgb: np.ndarray, alpha: np.ndarray | None, name: str, max_width: int) -> bytes:
    height, width = rgb.shape[:2]
    if width > max_width:
        scale = max_width / float(width)
        size = (max_width, max(1, int(height * scale)))
        rgb = cv2.resize(rgb, size, interpolation=cv2.INTER_AREA)
        if alpha is not None:
            alpha = cv2.resize(alpha, size, interpolation=cv2.INTER_AREA)

    buffer = io.BytesIO()
    if alpha is not None or name.endswith(".png"):
        image = Image.fromarray(rgb, mode="RGB")
        if alpha is not None:
            image.putalpha(Image.fromarray(alpha, mode="L"))
        image.save(buffer, format="PNG", optimize=True)
    else:
        Image.fromarray(rgb, mode="RGB").save(buffer, format="JPEG", quality=88, subsampling=1)
    return buffer.getvalue()


def build(max_width: int) -> dict[str, bytes]:
    gradient = demo.flat_gradient(1400, 1000)
    stamped, stamp_mask = demo.add_date_stamp(gradient)
    texture = demo.woven_texture(1200, 900)
    badged, badge_mask = demo.add_small_overlay_badge(texture)
    painting = demo.painted_illustration(1400, 1000)
    signed, signature_box = demo.add_signature(painting)
    credited, credit_box = demo.add_copyright_line(painting)
    stock = demo.add_stock_watermark(painting)
    lines = demo.line_artwork(1000, 1000)
    sticker_rgb, sticker_alpha = demo.alpha_sticker(560)

    files: dict[str, bytes] = {
        "backdrop-clean.jpg": _encode(gradient, None, "backdrop-clean.jpg", max_width),
        "backdrop-datestamp.jpg": _encode(stamped, None, "backdrop-datestamp.jpg", max_width),
        "backdrop-datestamp-mask.png": _encode(
            cv2.cvtColor(stamp_mask, cv2.COLOR_GRAY2RGB),
            None,
            "backdrop-datestamp-mask.png",
            max_width,
        ),
        "canvas-texture-clean.jpg": _encode(texture, None, "canvas-texture-clean.jpg", max_width),
        "canvas-texture-badge.jpg": _encode(badged, None, "canvas-texture-badge.jpg", max_width),
        "canvas-texture-badge-mask.png": _encode(
            cv2.cvtColor(badge_mask, cv2.COLOR_GRAY2RGB),
            None,
            "canvas-texture-badge-mask.png",
            max_width,
        ),
        "painted-landscape.jpg": _encode(painting, None, "painted-landscape.jpg", max_width),
        "painted-landscape-signed.jpg": _encode(
            signed, None, "painted-landscape-signed.jpg", max_width
        ),
        "painted-landscape-credit.jpg": _encode(
            credited, None, "painted-landscape-credit.jpg", max_width
        ),
        "painted-landscape-stock.jpg": _encode(
            stock, None, "painted-landscape-stock.jpg", max_width
        ),
        "line-artwork.jpg": _encode(lines, None, "line-artwork.jpg", max_width),
        "alpha-sticker.png": _encode(sticker_rgb, sticker_alpha, "alpha-sticker.png", max_width),
    }

    manifest = {
        "generator": "artrestore_imaging.demo",
        "seed": demo.DEMO_SEED,
        "license": "Generated procedurally for this repository; no third-party rights apply.",
        "protected_boxes": {
            "painted-landscape-signed.jpg": {"signature": list(signature_box)},
            "painted-landscape-credit.jpg": {"copyright_notice": list(credit_box)},
        },
        "files": sorted(files),
    }
    # Trailing newline so the generated file matches Prettier's output.
    files["manifest.json"] = (json.dumps(manifest, indent=2) + "\n").encode()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--web", action="store_true", help="also copy into apps/web/public/demo")
    parser.add_argument("--max-width", type=int, default=WEB_MAX_WIDTH)
    args = parser.parse_args()

    files = build(args.max_width)
    args.output.mkdir(parents=True, exist_ok=True)
    for name, payload in files.items():
        (args.output / name).write_bytes(payload)
        print(f"wrote {args.output / name} ({len(payload) // 1024} KiB)")

    if args.web:
        WEB_PUBLIC.mkdir(parents=True, exist_ok=True)
        for name, payload in files.items():
            (WEB_PUBLIC / name).write_bytes(payload)
        print(f"copied {len(files)} files into {WEB_PUBLIC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
