#!/usr/bin/env python3
"""Seed a development database with a demo account and two ready projects.

Every image is generated by :mod:`artrestore_imaging.demo`, so the seed data
carries no third-party rights - which is the only defensible way to ship demo
content for a product about respecting ownership.

    python scripts/seed.py                 # create or refresh the demo account
    python scripts/seed.py --reset         # delete it first, then recreate
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
for package in ("services/image-processing/src", "services/timelapse-renderer/src", "apps/api/src"):
    sys.path.insert(0, str(REPO_ROOT / package))

import numpy as np  # noqa: E402
from artrestore_api import models  # noqa: E402
from artrestore_api.config import get_settings  # noqa: E402
from artrestore_api.db import Base, get_engine, session_scope  # noqa: E402
from artrestore_api.security.passwords import hash_password  # noqa: E402
from artrestore_api.services import consent as consent_service  # noqa: E402
from artrestore_api.services import projects as project_service  # noqa: E402
from artrestore_api.storage import build_object_key, get_storage  # noqa: E402
from artrestore_imaging import demo, encode_mask_png, load_safe_raster  # noqa: E402
from sqlalchemy import select  # noqa: E402

DEMO_EMAIL = "demo@example.com"
DEMO_PASSWORD = "demo-account-passphrase"


def _store_image(
    storage, *, user_id: str, project_id: str, asset_type: str, name: str, data: bytes
):
    key = build_object_key(user_id, project_id, asset_type, name)
    storage.put_bytes(key, data, "image/png")
    return key


def _add_image_asset(
    session, storage, *, project, asset_type: str, name: str, data: bytes, order=0
):
    raster = load_safe_raster(data)
    key = _store_image(
        storage,
        user_id=project.user_id,
        project_id=project.id,
        asset_type=asset_type,
        name=name,
        data=data,
    )
    asset = models.Asset(
        project_id=project.id,
        type=asset_type,
        storage_key=key,
        mime_type="image/png",
        width=raster.width,
        height=raster.height,
        byte_size=len(data),
        order_index=order,
        upload_complete=True,
        asset_metadata={
            **raster.metadata_summary,
            "color_mode": "RGB",
            "has_alpha": raster.has_alpha,
            "megapixels": round(raster.width * raster.height / 1_000_000, 3),
            "seeded": True,
        },
    )
    session.add(asset)
    session.flush()
    return asset


def seed(reset: bool = False) -> dict:
    settings = get_settings()
    Base.metadata.create_all(get_engine())
    storage = get_storage()

    with session_scope() as session:
        existing = session.execute(
            select(models.User).where(models.User.email == DEMO_EMAIL)
        ).scalar_one_or_none()
        if existing is not None:
            if not reset:
                return {
                    "status": "already_seeded",
                    "email": DEMO_EMAIL,
                    "projects": len(existing.projects),
                }
            storage.delete_prefix(f"users/{existing.id}/")
            session.delete(existing)
            session.flush()

        user = models.User(
            email=DEMO_EMAIL,
            name="Demo Artist",
            password_hash=hash_password(DEMO_PASSWORD),
            retention_preferences={"retention_days": settings.default_retention_days},
        )
        session.add(user)
        session.flush()

        for consent_type in ("terms", "privacy", "authorized_use_policy"):
            consent_service.record_consent(session, user=user, consent_type=consent_type)

        # --- Project 1: an authorized date-stamp cleanup ---------------------
        cleanup = project_service.create_project(
            session, user=user, name="Studio backdrop - date stamp", project_type="cleanup"
        )
        cleanup.status = "ready"
        background = demo.flat_gradient(1200, 900)
        stamped, stamp_mask = demo.add_date_stamp(background)

        _add_image_asset(
            session,
            storage,
            project=cleanup,
            asset_type="source",
            name="backdrop-datestamp.png",
            data=demo.to_png(stamped),
        )
        _add_image_asset(
            session,
            storage,
            project=cleanup,
            asset_type="source_preview",
            name="backdrop-datestamp-preview.png",
            data=demo.to_png(demo.flat_gradient(600, 450)),
        )
        consent_service.record_consent(
            session,
            user=user,
            consent_type="ownership_confirmation",
            project=cleanup,
            context={"seeded": True},
        )

        # A ready-made mask over the stamp, so the editor opens with something
        # to look at rather than a blank canvas.
        ys, xs = np.nonzero(stamp_mask)
        mask_key = build_object_key(user.id, cleanup.id, "mask", "v1.png")
        storage.put_bytes(mask_key, encode_mask_png(stamp_mask), "image/png")
        session.add(
            models.Mask(
                project_id=cleanup.id,
                version=1,
                storage_key=mask_key,
                editor_state={
                    "version": 1,
                    "image": {"width": 1200, "height": 900},
                    "regions": [
                        {
                            "id": "seed-rect",
                            "type": "rect",
                            "x": int(xs.min()) - 6,
                            "y": int(ys.min()) - 6,
                            "width": int(xs.max() - xs.min()) + 12,
                            "height": int(ys.max() - ys.min()) + 12,
                            "mode": "add",
                        }
                    ],
                    "adjustments": {"expand": 1, "feather": 3, "blur": 0},
                },
            )
        )

        # --- Project 2: a timelapse reconstruction ---------------------------
        timelapse = project_service.create_project(
            session, user=user, name="Painted landscape - process video", project_type="timelapse"
        )
        timelapse.status = "ready"
        painting = demo.painted_illustration(1200, 900)
        _add_image_asset(
            session,
            storage,
            project=timelapse,
            asset_type="source",
            name="painted-landscape.png",
            data=demo.to_png(painting),
        )
        _add_image_asset(
            session,
            storage,
            project=timelapse,
            asset_type="source_preview",
            name="painted-landscape-preview.png",
            data=demo.to_png(demo.painted_illustration(600, 450)),
        )
        consent_service.record_consent(
            session,
            user=user,
            consent_type="ownership_confirmation",
            project=timelapse,
            context={"seeded": True},
        )

        from artrestore_timelapse import build_plan

        for stage in build_plan("sketch_to_colour", total_seconds=15):
            session.add(
                models.TimelapseStage(
                    project_id=timelapse.id,
                    stage_type=stage.stage_type,
                    label=stage.label,
                    order_index=stage.order_index,
                    duration=stage.duration,
                    enabled=stage.enabled,
                    settings=stage.settings,
                )
            )

        return {
            "status": "seeded",
            "email": DEMO_EMAIL,
            "password": DEMO_PASSWORD,
            "projects": 2,
        }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reset", action="store_true", help="delete the demo account first")
    args = parser.parse_args()

    result = seed(reset=args.reset)
    if result["status"] == "already_seeded":
        print(f"Demo account {result['email']} already exists. Use --reset to recreate it.")
    else:
        print("Seeded the demo account:")
        print(f"  email:    {result['email']}")
        print(f"  password: {result['password']}")
        print(f"  projects: {result['projects']} (one cleanup, one timelapse)")
        print("\nAll seed images are generated procedurally; none carry third-party rights.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
